spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/scheduleDB
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: validate
  sql:
    init:
      mode: always
      data-locations: classpath:/sql/data.sql
  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: true
  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
