INSERT INTO course
select *
from (values (1, 'Principles of Economics', 'Learn about the fundamentals of economics'),
             (2, 'World History: Ancient Civilizations', 'Explore the history of ancient civilizations'),
             (3, 'Creative Writing Workshop', 'Develop your writing skills in a creative environment'),
             (4, 'Introduction to Psychology', 'Learn the basics of psychology'),
             (5, 'Business Ethics and Social Responsibility',
              'Explore ethical issues in business and the role of social responsibility'),
             (6, 'Human Anatomy and Physiology', 'Study the human body and its functions'),
             (7, 'Principles of Marketing', 'Learn the basics of marketing'),
             (8, 'Environmental Science and Sustainability',
              'Study the science of the environment and explore issues of sustainability'),
             (9, 'Fundamentals of Graphic Design', 'Learn the basics of graphic design'),
             (10, 'Introduction to Computer Science',
              'An introduction to computer science principles and programming')) sourse_data
where not exists(select null from course)
on conflict (id) DO NOTHING;


INSERT INTO groups
select *
from (values (1, 'YS-27'),
             (2, 'HV-14'),
             (3, 'QM-09'),
             (4, 'ZF-83'),
             (5, 'RG-52'),
             (6, 'PL-41'),
             (7, 'KX-76'),
             (8, 'ND-98'),
             (9, 'TC-63'),
             (10, 'WU-48'),
             (11, 'Students without group')) sourse_data
where not exists(select null from groups)
on conflict (id) DO NOTHING;

INSERT INTO users (role, first_name, last_name, email)
select *
from (VALUES ('teacher', 'John', 'Smith', 'JohnSmith@gmail.com'),
             ('teacher', 'Emily', 'Johnson', 'EmilyJohnson@gmail.com'),
             ('teacher', 'Michael', 'Davis', 'MichaelDavis@gmail.com'),
             ('teacher', 'Sarah', 'Wilson', 'SarahWilson@gmail.com'),
             ('teacher', 'Robert', 'Taylor', 'RobertTaylor@gmail.com'),
             ('teacher', 'Jessica', 'Brown', 'JessicaBrown@gmail.com'),
             ('teacher', 'William', 'Moore', 'WilliamMoore@gmail.com'),
             ('teacher', 'Olivia', 'Anderson', 'OliviaAnderson@gmail.com')) sourse_data
where not exists(select null from users where role = 'teacher')
on conflict (id) DO NOTHING;

INSERT INTO classroom
select *
from (VALUES (1, 'Room 101'),
             (2, 'Room 102'),
             (3, 'Room 103'),
             (4, 'Room 104'),
             (5, 'Room 105'),
             (6, 'Room 201'),
             (7, 'Room 202'),
             (8, 'Room 203'),
             (9, 'Room 204'),
             (10, 'Room 205')) sourse_data
where not exists(select null from classroom)
on conflict (id) DO NOTHING;

INSERT INTO users (role, first_name, last_name, email, group_id)
select *
from (values ('student', 'Liam', 'Jones', 'LiamJones@gmail.com', 2),
             ('student', 'Harper', 'Robinson', 'HarperRobinson@gmail.com', 10),
             ('student', 'Lucas', 'Thompson', 'LucasThompson@gmail.com', 1),
             ('student', 'Carter', 'Clark', 'CarterClark@gmail.com', 9),
             ('student', 'Amelia', 'Martinez', 'AmeliaMartinez@gmail.com', 3),
             ('student', 'Isabella', 'Miller', 'IsabellaMiller@gmail.com', 5),
             ('student', 'Sophia', 'Lee', 'SophiaLee@gmail.com', 5),
             ('student', 'Mia', 'Hall', 'MiaHall@gmail.com', 9),
             ('student', 'Emma', 'Jones', 'EmmaJones@gmail.com', 2),
             ('student', 'Caden', 'Smith', 'CadenSmith@gmail.com', 5),
             ('student', 'Amelia', 'Thomas', 'AmeliaThomas@gmail.com', 5),
             ('student', 'Grayson', 'Garcia', 'GraysonGarcia@gmail.com', 11),
             ('student', 'Liam', 'Garcia', 'LiamGarcia@gmail.com', 2),
             ('student', 'Ava', 'Smith', 'AvaSmith@gmail.com', 2),
             ('student', 'Abigail', 'Robinson', 'AbigailRobinson@gmail.com', 5),
             ('student', 'Carter', 'Thomas', 'CarterThomas@gmail.com', 6),
             ('student', 'Amelia', 'Rodriguez', 'AmeliaRodriguez@gmail.com', 4),
             ('student', 'Olivia', 'Martinez', 'OliviaMartinez@gmail.com', 4),
             ('student', 'Evelyn', 'Rodriguez', 'EvelynRodriguez@gmail.com', 2),
             ('student', 'Noah', 'Lee', 'NoahLee@gmail.com', 9),
             ('student', 'Olivia', 'Taylor', 'OliviaTaylor@gmail.com', 3),
             ('student', 'Harper', 'Thompson', 'HarperThompson@gmail.com', 4),
             ('student', 'Noah', 'Williams', 'NoahWilliams@gmail.com', 3),
             ('student', 'Carter', 'Lewis', 'CarterLewis@gmail.com', 8),
             ('student', 'Caden', 'Thompson', 'CadenThompson@gmail.com', 7),
             ('student', 'Jackson', 'Jones', 'JacksonJones@gmail.com', 8),
             ('student', 'Sophia', 'Thomas', 'SophiaThomas@gmail.com', 6),
             ('student', 'Sophia', 'Brown', 'SophiaBrown@gmail.com', 3),
             ('student', 'Ava', 'Rodriguez', 'AvaRodriguez@gmail.com', 6),
             ('student', 'Carter', 'Smith', 'CarterSmith@gmail.com', 11),
             ('student', 'Evelyn', 'Lee', 'EvelynLee@gmail.com', 6),
             ('student', 'Caden', 'Clark', 'CadenClark@gmail.com', 11),
             ('student', 'Ava', 'Hall', 'AvaHall@gmail.com', 5),
             ('student', 'Noah', 'Garcia', 'NoahGarcia@gmail.com', 6),
             ('student', 'Harper', 'Garcia', 'HarperGarcia@gmail.com', 6),
             ('student', 'Ava', 'Miller', 'AvaMiller@gmail.com', 5),
             ('student', 'Harper', 'Jones', 'HarperJones@gmail.com', 9),
             ('student', 'Lucas', 'Taylor', 'LucasTaylor@gmail.com', 2),
             ('student', 'Sophia', 'Rodriguez', 'SophiaRodriguez@gmail.com', 8),
             ('student', 'Elijah', 'Williams', 'ElijahWilliams@gmail.com', 4),
             ('student', 'Ava', 'Williams', 'AvaWilliams@gmail.com', 10),
             ('student', 'Emma', 'Martinez', 'EmmaMartinez@gmail.com', 6),
             ('student', 'Lucas', 'Anderson', 'LucasAnderson@gmail.com', 7),
             ('student', 'Olivia', 'Davis', 'OliviaDavis@gmail.com', 10),
             ('student', 'Isabella', 'Anderson', 'IsabellaAnderson@gmail.com', 2),
             ('student', 'Emma', 'Taylor', 'EmmaTaylor@gmail.com', 1),
             ('student', 'Lucas', 'Lee', 'LucasLee@gmail.com', 7),
             ('student', 'Elijah', 'Garcia', 'ElijahGarcia@gmail.com', 7),
             ('student', 'Jackson', 'Robinson', 'JacksonRobinson@gmail.com', 10),
             ('student', 'Olivia', 'Rodriguez', 'OliviaRodriguez@gmail.com', 7),
             ('student', 'Noah', 'Clark', 'NoahClark@gmail.com', 11),
             ('student', 'Elijah', 'Robinson', 'ElijahRobinson@gmail.com', 3),
             ('student', 'Isabella', 'Thompson', 'IsabellaThompson@gmail.com', 5),
             ('student', 'Olivia', 'Smith', 'OliviaSmith@gmail.com', 9),
             ('student', 'Jackson', 'Hall', 'JacksonHall@gmail.com', 5),
             ('student', 'Amelia', 'Brown', 'AmeliaBrown@gmail.com', 2),
             ('student', 'Emma', 'Brown', 'EmmaBrown@gmail.com', 10),
             ('student', 'Grayson', 'Robinson', 'GraysonRobinson@gmail.com', 10),
             ('student', 'Emma', 'Clark', 'EmmaClark@gmail.com', 6),
             ('student', 'Elijah', 'Johnson', 'ElijahJohnson@gmail.com', 2),
             ('student', 'Ava', 'Thompson', 'AvaThompson@gmail.com', 11),
             ('student', 'Caden', 'Johnson', 'CadenJohnson@gmail.com', 7),
             ('student', 'Emma', 'Smith', 'EmmaSmith@gmail.com', 8),
             ('student', 'Lucas', 'Hall', 'LucasHall@gmail.com', 8),
             ('student', 'Noah', 'Thompson', 'NoahThompson@gmail.com', 9),
             ('student', 'Olivia', 'Clark', 'OliviaClark@gmail.com', 10),
             ('student', 'Lucas', 'Smith', 'LucasSmith@gmail.com', 1),
             ('student', 'Abigail', 'Clark', 'AbigailClark@gmail.com', 7),
             ('student', 'Abigail', 'Garcia', 'AbigailGarcia@gmail.com', 11),
             ('student', 'Amelia', 'Johnson', 'AmeliaJohnson@gmail.com', 8),
             ('student', 'Aiden', 'Thompson', 'AidenThompson@gmail.com', 6),
             ('student', 'Emma', 'Robinson', 'EmmaRobinson@gmail.com', 9),
             ('student', 'Elijah', 'Wilson', 'ElijahWilson@gmail.com', 8),
             ('student', 'Isabella', 'Clark', 'IsabellaClark@gmail.com', 10),
             ('student', 'Carter', 'Robinson', 'CarterRobinson@gmail.com', 10),
             ('student', 'Mia', 'Miller', 'MiaMiller@gmail.com', 5),
             ('student', 'Elijah', 'Thomas', 'ElijahThomas@gmail.com', 3),
             ('student', 'Sophia', 'Robinson', 'SophiaRobinson@gmail.com', 11),
             ('student', 'Noah', 'Taylor', 'NoahTaylor@gmail.com', 2),
             ('student', 'Elijah', 'Clark', 'ElijahClark@gmail.com', 8),
             ('student', 'Emma', 'Thomas', 'EmmaThomas@gmail.com', 11),
             ('student', 'Oliver', 'Garcia', 'OliverGarcia@gmail.com', 10),
             ('student', 'Evelyn', 'Wilson', 'EvelynWilson@gmail.com', 3),
             ('student', 'Oliver', 'Lewis', 'OliverLewis@gmail.com', 10),
             ('student', 'Lucas', 'Davis', 'LucasDavis@gmail.com', 8),
             ('student', 'Oliver', 'Rodriguez', 'OliverRodriguez@gmail.com', 1),
             ('student', 'Liam', 'Williams', 'LiamWilliams@gmail.com', 8),
             ('student', 'Evelyn', 'Hall', 'EvelynHall@gmail.com', 1),
             ('student', 'Lucas', 'Jones', 'LucasJones@gmail.com', 9),
             ('student', 'Olivia', 'Brown', 'OliviaBrown@gmail.com', 8),
             ('student', 'Abigail', 'Wilson', 'AbigailWilson@gmail.com', 3),
             ('student', 'Emma', 'Johnson', 'EmmaJohnson@gmail.com', 11),
             ('student', 'Caden', 'Robinson', 'CadenRobinson@gmail.com', 8),
             ('student', 'Mia', 'Robinson', 'MiaRobinson@gmail.com', 7),
             ('student', 'Liam', 'Brown', 'LiamBrown@gmail.com', 3),
             ('student', 'Ava', 'Jones', 'AvaJones@gmail.com', 4),
             ('student', 'Liam', 'Anderson', 'LiamAnderson@gmail.com', 7),
             ('student', 'Noah', 'Miller', 'NoahMiller@gmail.com', 10),
             ('student', 'Mia', 'Lee', 'MiaLee@gmail.com', 3),
             ('student', 'Evelyn', 'Johnson', 'EvelynJohnson@gmail.com', 4),
             ('student', 'Harper', 'Rodriguez', 'HarperRodriguez@gmail.com', 6),
             ('student', 'Abigail', 'Johnson', 'AbigailJohnson@gmail.com', 8),
             ('student', 'Olivia', 'Miller', 'OliviaMiller@gmail.com', 11),
             ('student', 'Aiden', 'Jones', 'AidenJones@gmail.com', 9),
             ('student', 'Harper', 'Smith', 'HarperSmith@gmail.com', 11),
             ('student', 'Caden', 'Hall', 'CadenHall@gmail.com', 6),
             ('student', 'Amelia', 'Thompson', 'AmeliaThompson@gmail.com', 4),
             ('student', 'Sophia', 'Davis', 'SophiaDavis@gmail.com', 5),
             ('student', 'Oliver', 'Martinez', 'OliverMartinez@gmail.com', 5),
             ('student', 'Harper', 'Martinez', 'HarperMartinez@gmail.com', 1),
             ('student', 'Aiden', 'Rodriguez', 'AidenRodriguez@gmail.com', 5),
             ('student', 'Lucas', 'Rodriguez', 'LucasRodriguez@gmail.com', 8),
             ('student', 'Grayson', 'Anderson', 'GraysonAnderson@gmail.com', 9),
             ('student', 'Caden', 'Lee', 'CadenLee@gmail.com', 8),
             ('student', 'Lucas', 'Martinez', 'LucasMartinez@gmail.com', 5),
             ('student', 'Jackson', 'Rodriguez', 'JacksonRodriguez@gmail.com', 11),
             ('student', 'Noah', 'Jones', 'NoahJones@gmail.com', 2),
             ('student', 'Isabella', 'Taylor', 'IsabellaTaylor@gmail.com', 8),
             ('student', 'Amelia', 'Jones', 'AmeliaJones@gmail.com', 2),
             ('student', 'Lucas', 'Williams', 'LucasWilliams@gmail.com', 2),
             ('student', 'Jackson', 'Anderson', 'JacksonAnderson@gmail.com', 4),
             ('student', 'Carter', 'Hall', 'CarterHall@gmail.com', 3),
             ('student', 'Jackson', 'Brown', 'JacksonBrown@gmail.com', 5),
             ('student', 'Jackson', 'Clark', 'JacksonClark@gmail.com', 6),
             ('student', 'Emma', 'Davis', 'EmmaDavis@gmail.com', 8),
             ('student', 'Isabella', 'Lee', 'IsabellaLee@gmail.com', 2),
             ('student', 'Carter', 'Taylor', 'CarterTaylor@gmail.com', 2),
             ('student', 'Grayson', 'Rodriguez', 'GraysonRodriguez@gmail.com', 6),
             ('student', 'Isabella', 'Wilson', 'IsabellaWilson@gmail.com', 5),
             ('student', 'Caden', 'Davis', 'CadenDavis@gmail.com', 10),
             ('student', 'Abigail', 'Thomas', 'AbigailThomas@gmail.com', 2),
             ('student', 'Liam', 'Johnson', 'LiamJohnson@gmail.com', 10),
             ('student', 'Carter', 'Thompson', 'CarterThompson@gmail.com', 8),
             ('student', 'Oliver', 'Jones', 'OliverJones@gmail.com', 11),
             ('student', 'Oliver', 'Anderson', 'OliverAnderson@gmail.com', 5),
             ('student', 'Olivia', 'Jones', 'OliviaJones@gmail.com', 8),
             ('student', 'Oliver', 'Miller', 'OliverMiller@gmail.com', 8),
             ('student', 'Elijah', 'Lee', 'ElijahLee@gmail.com', 9),
             ('student', 'Grayson', 'Jones', 'GraysonJones@gmail.com', 6),
             ('student', 'Ava', 'Robinson', 'AvaRobinson@gmail.com', 6),
             ('student', 'Ava', 'Thomas', 'AvaThomas@gmail.com', 1),
             ('student', 'Lucas', 'Miller', 'LucasMiller@gmail.com', 4),
             ('student', 'Amelia', 'Anderson', 'AmeliaAnderson@gmail.com', 2),
             ('student', 'Abigail', 'Miller', 'AbigailMiller@gmail.com', 4),
             ('student', 'Noah', 'Davis', 'NoahDavis@gmail.com', 10),
             ('student', 'Isabella', 'Hall', 'IsabellaHall@gmail.com', 9),
             ('student', 'Emma', 'Thompson', 'EmmaThompson@gmail.com', 1),
             ('student', 'Aiden', 'Robinson', 'AidenRobinson@gmail.com', 5),
             ('student', 'Caden', 'Rodriguez', 'CadenRodriguez@gmail.com', 7),
             ('student', 'Carter', 'Miller', 'CarterMiller@gmail.com', 11),
             ('student', 'Harper', 'Lee', 'HarperLee@gmail.com', 8),
             ('student', 'Ava', 'Wilson', 'AvaWilson@gmail.com', 9),
             ('student', 'Elijah', 'Smith', 'ElijahSmith@gmail.com', 4),
             ('student', 'Amelia', 'Lewis', 'AmeliaLewis@gmail.com', 2),
             ('student', 'Aiden', 'Lewis', 'AidenLewis@gmail.com', 10),
             ('student', 'Liam', 'Thompson', 'LiamThompson@gmail.com', 8),
             ('student', 'Aiden', 'Davis', 'AidenDavis@gmail.com', 8),
             ('student', 'Carter', 'Jones', 'CarterJones@gmail.com', 2),
             ('student', 'Evelyn', 'Jones', 'EvelynJones@gmail.com', 5),
             ('student', 'Oliver', 'Smith', 'OliverSmith@gmail.com', 9),
             ('student', 'Elijah', 'Thompson', 'ElijahThompson@gmail.com', 8),
             ('student', 'Grayson', 'Smith', 'GraysonSmith@gmail.com', 6),
             ('student', 'Mia', 'Smith', 'MiaSmith@gmail.com', 5),
             ('student', 'Mia', 'Lewis', 'MiaLewis@gmail.com', 2),
             ('student', 'Elijah', 'Rodriguez', 'ElijahRodriguez@gmail.com', 8),
             ('student', 'Liam', 'Davis', 'LiamDavis@gmail.com', 2),
             ('student', 'Mia', 'Rodriguez', 'MiaRodriguez@gmail.com', 6),
             ('student', 'Isabella', 'Lewis', 'IsabellaLewis@gmail.com', 2),
             ('student', 'Ava', 'Garcia', 'AvaGarcia@gmail.com', 9),
             ('student', 'Evelyn', 'Taylor', 'EvelynTaylor@gmail.com', 1),
             ('student', 'Abigail', 'Taylor', 'AbigailTaylor@gmail.com', 1),
             ('student', 'Grayson', 'Clark', 'GraysonClark@gmail.com', 9),
             ('student', 'Aiden', 'Martinez', 'AidenMartinez@gmail.com', 2),
             ('student', 'Abigail', 'Lewis', 'AbigailLewis@gmail.com', 11),
             ('student', 'Isabella', 'Martinez', 'IsabellaMartinez@gmail.com', 11),
             ('student', 'Harper', 'Taylor', 'HarperTaylor@gmail.com', 9),
             ('student', 'Elijah', 'Taylor', 'ElijahTaylor@gmail.com', 2),
             ('student', 'Evelyn', 'Williams', 'EvelynWilliams@gmail.com', 10),
             ('student', 'Aiden', 'Smith', 'AidenSmith@gmail.com', 3),
             ('student', 'Liam', 'Wilson', 'LiamWilson@gmail.com', 10),
             ('student', 'Caden', 'Williams', 'CadenWilliams@gmail.com', 6),
             ('student', 'Amelia', 'Davis', 'AmeliaDavis@gmail.com', 7),
             ('student', 'Carter', 'Rodriguez', 'CarterRodriguez@gmail.com', 4),
             ('student', 'Lucas', 'Garcia', 'LucasGarcia@gmail.com', 8),
             ('student', 'Grayson', 'Lee', 'GraysonLee@gmail.com', 7),
             ('student', 'Sophia', 'Johnson', 'SophiaJohnson@gmail.com', 6),
             ('student', 'Abigail', 'Martinez', 'AbigailMartinez@gmail.com', 8),
             ('student', 'Emma', 'Williams', 'EmmaWilliams@gmail.com', 10),
             ('student', 'Jackson', 'Lee', 'JacksonLee@gmail.com', 4),
             ('student', 'Carter', 'Garcia', 'CarterGarcia@gmail.com', 8),
             ('student', 'Carter', 'Williams', 'CarterWilliams@gmail.com', 2),
             ('student', 'Sophia', 'Taylor', 'SophiaTaylor@gmail.com', 6),
             ('student', 'Emma', 'Garcia', 'EmmaGarcia@gmail.com', 11),
             ('student', 'Evelyn', 'Anderson', 'EvelynAnderson@gmail.com', 2),
             ('student', 'Amelia', 'Williams', 'AmeliaWilliams@gmail.com', 2),
             ('student', 'Caden', 'Anderson', 'CadenAnderson@gmail.com', 9),
             ('student', 'Carter', 'Davis', 'CarterDavis@gmail.com', 10),
             ('student', 'Mia', 'Williams', 'MiaWilliams@gmail.com', 6),
             ('student', 'Caden', 'Miller', 'CadenMiller@gmail.com', 5),
             ('student', 'Mia', 'Thomas', 'MiaThomas@gmail.com', 8),
             ('student', 'Student', 'Student', 'StudentStudent@gmail.com', 1)) sourse_data
where not exists(select null from users where role = 'student')
on conflict (id) DO NOTHING;

INSERT INTO users (role, first_name, last_name, email)
select *
from (VALUES ('staff', 'Lucas', 'Smith', 'LucasSmithSt@gmail.com'),
             ('staff', 'Emily', 'Taylor', 'EmilyTaylor@gmail.com'),
             ('staff', 'Olivia', 'Davis', 'OliviaJDavis@gmail.com')) sourse_data
where not exists(select null from users where role = 'staff')
on conflict (id) DO NOTHING;
