
            INSERT INTO course select * from (
            values (1, 'Principles of Economics', 'Learn about the fundamentals of economics'),
                   (2, 'World History: Ancient Civilizations', 'Explore the history of ancient civilizations'),
                   (3, 'Creative Writing Workshop', 'Develop your writing skills in a creative environment'),
                   (4, 'Introduction to Psychology', 'Learn the basics of psychology'),
                   (5, 'Business Ethics and Social Responsibility',
                    'Explore ethical issues in business and the role of social responsibility'),
                   (6, 'Human Anatomy and Physiology', 'Study the human body and its functions'),
                   (7, 'Principles of Marketing', 'Learn the basics of marketing'),
                   (8, 'Environmental Science and Sustainability',
                    'Study the science of the environment and explore issues of sustainability'),
                   (9, 'Fundamentals of Graphic Design', 'Learn the basics of graphic design'),
                   (10, 'Introduction to Computer Science',
                    'An introduction to computer science principles and programming')) sourse_data
            where not exists(select null from course)
            on conflict (id) DO NOTHING;


            INSERT INTO groups select * from (
            values (1, 'YS-27'),
                   (2, 'HV-14'),
                   (3, 'QM-09'),
                   (4, 'ZF-83'),
                   (5, 'RG-52'),
                   (6, 'PL-41'),
                   (7, 'KX-76'),
                   (8, 'ND-98'),
                   (9, 'TC-63'),
                   (10, 'WU-48'),
                   (11, 'Students without group')) sourse_data
            where not exists(select null from groups)
            on conflict (id) DO NOTHING ;



            INSERT INTO teacher select * from (
            VALUES (1, 'John', 'Smith'),
                   (2, 'Emily', 'Johnson'),
                   (3, 'Michael', 'Davis'),
                   (4, 'Sarah', 'Wilson'),
                   (5, 'Robert', 'Taylor'),
                   (6, 'Jessica', 'Brown'),
                   (7, 'William', 'Moore'),
                   (8, 'Olivia', 'Anderson')) sourse_data
            where not exists(select null from teacher)
            on conflict (id) DO NOTHING ;

            INSERT INTO classroom select * from (
            VALUES (1, 'Room 101'),
                   (2, 'Room 102'),
                   (3, 'Room 103'),
                   (4, 'Room 104'),
                   (5, 'Room 105'),
                   (6, 'Room 201'),
                   (7, 'Room 202'),
                   (8, 'Room 203'),
                   (9, 'Room 204'),
                   (10, 'Room 205')) sourse_data
            where not exists(select null from classroom)
            on conflict (id) DO NOTHING ;

            INSERT INTO student select * from (
            values (1, 'Liam', 'Jones', 2),
                   (2, 'Harper', 'Robinson', 10),
                   (3, 'Lucas', 'Thompson', 1),
                   (4, 'Carter', 'Clark', 9),
                   (5, 'Amelia', 'Martinez', 3),
                   (6, 'Isabella', 'Miller', 5),
                   (7, 'Sophia', 'Lee', 5),
                   (8, 'Mia', 'Hall', 9),
                   (9, 'Emma', 'Jones', 2),
                   (10, 'Caden', 'Smith', 5),
                   (11, 'Amelia', 'Thomas', 5),
                   (12, 'Grayson', 'Garcia', 11),
                   (13, 'Liam', 'Garcia', 2),
                   (14, 'Ava', 'Smith', 2),
                   (15, 'Abigail', 'Robinson', 5),
                   (16, 'Carter', 'Thomas', 6),
                   (17, 'Amelia', 'Rodriguez', 4),
                   (18, 'Olivia', 'Martinez', 4),
                   (19, 'Evelyn', 'Rodriguez', 2),
                   (20, 'Noah', 'Lee', 9),
                   (21, 'Olivia', 'Taylor', 3),
                   (22, 'Harper', 'Thompson', 4),
                   (23, 'Noah', 'Williams', 3),
                   (24, 'Carter', 'Lewis', 8),
                   (25, 'Caden', 'Thompson', 7),
                   (26, 'Jackson', 'Jones', 8),
                   (27, 'Sophia', 'Thomas', 6),
                   (28, 'Sophia', 'Brown', 3),
                   (29, 'Ava', 'Rodriguez', 6),
                   (30, 'Carter', 'Smith', 11),
                   (31, 'Evelyn', 'Lee', 6),
                   (32, 'Caden', 'Clark', 11),
                   (33, 'Ava', 'Hall', 5),
                   (34, 'Noah', 'Garcia', 6),
                   (35, 'Harper', 'Garcia', 6),
                   (36, 'Ava', 'Miller', 5),
                   (37, 'Harper', 'Jones', 9),
                   (38, 'Lucas', 'Taylor', 2),
                   (39, 'Sophia', 'Rodriguez', 8),
                   (40, 'Elijah', 'Williams', 4),
                   (41, 'Ava', 'Williams', 10),
                   (42, 'Emma', 'Martinez', 6),
                   (43, 'Lucas', 'Anderson', 7),
                   (44, 'Olivia', 'Davis', 10),
                   (45, 'Isabella', 'Anderson', 2),
                   (46, 'Emma', 'Taylor', 1),
                   (47, 'Lucas', 'Lee', 7),
                   (48, 'Elijah', 'Garcia', 7),
                   (49, 'Jackson', 'Robinson', 10),
                   (50, 'Olivia', 'Rodriguez', 7),
                   (51, 'Noah', 'Clark', 11),
                   (52, 'Elijah', 'Robinson', 3),
                   (53, 'Isabella', 'Thompson', 5),
                   (54, 'Olivia', 'Smith', 9),
                   (55, 'Jackson', 'Hall', 5),
                   (56, 'Amelia', 'Brown', 2),
                   (57, 'Emma', 'Brown', 10),
                   (58, 'Grayson', 'Robinson', 10),
                   (59, 'Emma', 'Clark', 6),
                   (60, 'Elijah', 'Johnson', 2),
                   (61, 'Ava', 'Thompson', 11),
                   (62, 'Caden', 'Johnson', 7),
                   (63, 'Emma', 'Smith', 8),
                   (64, 'Lucas', 'Hall', 8),
                   (65, 'Noah', 'Thompson', 9),
                   (66, 'Olivia', 'Clark', 10),
                   (67, 'Lucas', 'Smith', 1),
                   (68, 'Abigail', 'Clark', 7),
                   (69, 'Abigail', 'Garcia', 11),
                   (70, 'Amelia', 'Johnson', 8),
                   (71, 'Aiden', 'Thompson', 6),
                   (72, 'Emma', 'Robinson', 9),
                   (73, 'Elijah', 'Wilson', 8),
                   (74, 'Isabella', 'Clark', 10),
                   (75, 'Carter', 'Robinson', 10),
                   (76, 'Mia', 'Miller', 5),
                   (77, 'Elijah', 'Thomas', 3),
                   (78, 'Sophia', 'Robinson', 11),
                   (79, 'Noah', 'Taylor', 2),
                   (80, 'Elijah', 'Clark', 8),
                   (81, 'Emma', 'Thomas', 11),
                   (82, 'Oliver', 'Garcia', 10),
                   (83, 'Evelyn', 'Wilson', 3),
                   (84, 'Oliver', 'Lewis', 10),
                   (85, 'Lucas', 'Davis', 8),
                   (86, 'Oliver', 'Rodriguez', 1),
                   (87, 'Liam', 'Williams', 8),
                   (88, 'Evelyn', 'Hall', 1),
                   (89, 'Lucas', 'Jones', 9),
                   (90, 'Olivia', 'Brown', 8),
                   (91, 'Abigail', 'Wilson', 3),
                   (92, 'Emma', 'Johnson', 11),
                   (93, 'Caden', 'Robinson', 8),
                   (94, 'Mia', 'Robinson', 7),
                   (95, 'Liam', 'Brown', 3),
                   (96, 'Ava', 'Jones', 4),
                   (97, 'Liam', 'Anderson', 7),
                   (98, 'Noah', 'Miller', 10),
                   (99, 'Mia', 'Lee', 3),
                   (100, 'Evelyn', 'Johnson', 4),
                   (101, 'Harper', 'Rodriguez', 6),
                   (102, 'Abigail', 'Johnson', 8),
                   (103, 'Olivia', 'Miller', 11),
                   (104, 'Aiden', 'Jones', 9),
                   (105, 'Harper', 'Smith', 11),
                   (106, 'Caden', 'Hall', 6),
                   (107, 'Amelia', 'Thompson', 4),
                   (108, 'Sophia', 'Davis', 5),
                   (109, 'Oliver', 'Martinez', 5),
                   (110, 'Harper', 'Martinez', 1),
                   (111, 'Aiden', 'Rodriguez', 5),
                   (112, 'Lucas', 'Rodriguez', 8),
                   (113, 'Grayson', 'Anderson', 9),
                   (114, 'Caden', 'Lee', 8),
                   (115, 'Lucas', 'Martinez', 5),
                   (116, 'Jackson', 'Rodriguez', 11),
                   (117, 'Noah', 'Jones', 2),
                   (118, 'Isabella', 'Taylor', 8),
                   (119, 'Amelia', 'Jones', 2),
                   (120, 'Lucas', 'Williams', 2),
                   (121, 'Jackson', 'Anderson', 4),
                   (122, 'Carter', 'Hall', 3),
                   (123, 'Jackson', 'Brown', 5),
                   (124, 'Jackson', 'Clark', 6),
                   (125, 'Emma', 'Davis', 8),
                   (126, 'Isabella', 'Lee', 2),
                   (127, 'Carter', 'Taylor', 2),
                   (128, 'Grayson', 'Rodriguez', 6),
                   (129, 'Isabella', 'Wilson', 5),
                   (130, 'Caden', 'Davis', 10),
                   (131, 'Abigail', 'Thomas', 2),
                   (132, 'Liam', 'Johnson', 10),
                   (133, 'Carter', 'Thompson', 8),
                   (134, 'Oliver', 'Jones', 11),
                   (135, 'Oliver', 'Anderson', 5),
                   (136, 'Olivia', 'Jones', 8),
                   (137, 'Oliver', 'Miller', 8),
                   (138, 'Elijah', 'Lee', 9),
                   (139, 'Grayson', 'Jones', 6),
                   (140, 'Ava', 'Robinson', 6),
                   (141, 'Ava', 'Thomas', 1),
                   (142, 'Lucas', 'Miller', 4),
                   (143, 'Amelia', 'Anderson', 2),
                   (144, 'Abigail', 'Miller', 4),
                   (145, 'Noah', 'Davis', 10),
                   (146, 'Isabella', 'Hall', 9),
                   (147, 'Emma', 'Thompson', 1),
                   (148, 'Aiden', 'Robinson', 5),
                   (149, 'Caden', 'Rodriguez', 7),
                   (150, 'Carter', 'Miller', 11),
                   (151, 'Harper', 'Lee', 8),
                   (152, 'Ava', 'Wilson', 9),
                   (153, 'Elijah', 'Smith', 4),
                   (154, 'Amelia', 'Lewis', 2),
                   (155, 'Aiden', 'Lewis', 10),
                   (156, 'Liam', 'Thompson', 8),
                   (157, 'Aiden', 'Davis', 8),
                   (158, 'Carter', 'Jones', 2),
                   (159, 'Evelyn', 'Jones', 5),
                   (160, 'Oliver', 'Smith', 9),
                   (161, 'Elijah', 'Thompson', 8),
                   (162, 'Grayson', 'Smith', 6),
                   (163, 'Mia', 'Smith', 5),
                   (164, 'Mia', 'Lewis', 2),
                   (165, 'Elijah', 'Rodriguez', 8),
                   (166, 'Liam', 'Davis', 2),
                   (167, 'Mia', 'Rodriguez', 6),
                   (168, 'Isabella', 'Lewis', 2),
                   (169, 'Ava', 'Garcia', 9),
                   (170, 'Evelyn', 'Taylor', 1),
                   (171, 'Abigail', 'Taylor', 1),
                   (172, 'Grayson', 'Clark', 9),
                   (173, 'Aiden', 'Martinez', 2),
                   (174, 'Abigail', 'Lewis', 11),
                   (175, 'Isabella', 'Martinez', 11),
                   (176, 'Harper', 'Taylor', 9),
                   (177, 'Elijah', 'Taylor', 2),
                   (178, 'Evelyn', 'Williams', 10),
                   (179, 'Aiden', 'Smith', 3),
                   (180, 'Liam', 'Wilson', 10),
                   (181, 'Caden', 'Williams', 6),
                   (182, 'Amelia', 'Davis', 7),
                   (183, 'Carter', 'Rodriguez', 4),
                   (184, 'Lucas', 'Garcia', 8),
                   (185, 'Grayson', 'Lee', 7),
                   (186, 'Sophia', 'Johnson', 6),
                   (187, 'Abigail', 'Martinez', 8),
                   (188, 'Emma', 'Williams', 10),
                   (189, 'Jackson', 'Lee', 4),
                   (190, 'Carter', 'Garcia', 8),
                   (191, 'Carter', 'Williams', 2),
                   (192, 'Sophia', 'Taylor', 6),
                   (193, 'Emma', 'Garcia', 11),
                   (194, 'Evelyn', 'Anderson', 2),
                   (195, 'Amelia', 'Williams', 2),
                   (196, 'Caden', 'Anderson', 9),
                   (197, 'Carter', 'Davis', 10),
                   (198, 'Mia', 'Williams', 6),
                   (199, 'Caden', 'Miller', 5),
                   (200, 'Mia', 'Thomas', 8)) sourse_data
            where not exists(select null from student)
            on conflict (id) DO NOTHING
