create table classroom
(
    id             bigserial
        primary key,
    classroom_name varchar(10)
);

create table course
(
    id                 bigserial
        primary key,
    course_name        varchar(50),
    course_description varchar(100)
);

create table "groups"
(
    id         bigint generated by default as identity
        constraint pk_group
            primary key,
    group_name varchar(50)
);

create table student
(
    id         bigserial
        primary key,
    first_name varchar(20),
    last_name  varchar(20),
    group_id   bigint
);

create table teacher
(
    id         bigserial
        primary key,
    first_name varchar(20),
    last_name  varchar(20)
);

create table lesson
(
    id           bigint generated by default as identity
        constraint pk_lesson
            primary key,
    date         date,
    lesson_num   integer,
    course_id    bigint,
    group_id     bigint,
    classroom_id bigint,
    teacher_id   bigint,
    constraint date_lesson_teacher_class
        unique (date, lesson_num, teacher_id, classroom_id),
    constraint date_lesson_teacher
        unique (date, lesson_num, teacher_id),
    constraint date_lesson_class
        unique (date, lesson_num, classroom_id)
);