CREATE TABLE users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    role       VARCHAR(31),
    first_name VARCHAR(20),
    last_name  VARCHAR(20),
    email      VARCHAR(255),
    password   VARCHAR(255),
    group_id   BIGINT,
    CONSTRAINT pk_user PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_user_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT FK_USER_ON_GROUP FOREIGN KEY (group_id) REFERENCES groups (id);