INSERT INTO course (course_name, course_description)
values ('Principles of Economics', 'Learn about the fundamentals of economics'),
       ('World History: Ancient Civilizations', 'Explore the history of ancient civilizations'),
       ('Creative Writing Workshop', 'Develop your writing skills in a creative environment'),
       ('Introduction to Psychology', 'Learn the basics of psychology'),
       ('Business Ethics and Social Responsibility',
        'Explore ethical issues in business and the role of social responsibility'),
       ('Human Anatomy and Physiology', 'Study the human body and its functions'),
       ('Principles of Marketing', 'Learn the basics of marketing'),
       ('Environmental Science and Sustainability',
        'Study the science of the environment and explore issues of sustainability'),
       ('Fundamentals of Graphic Design', 'Learn the basics of graphic design'),
       ('Introduction to Computer Science', 'An introduction to computer science principles and programming');

INSERT INTO groups (group_name)
values ('YS-27'),
       ('HV-14'),
       ('QM-09'),
       ('ZF-83'),
       ('RG-52'),
       ('PL-41'),
       ('KX-76'),
       ('ND-98'),
       ('TC-63'),
       ('WU-48'),
       ('Students without group');

INSERT INTO teacher (first_name, last_name)
VALUES
    ('John', 'Smith'),
    ('Emily', 'Johnson'),
    ('Michael', 'Davis'),
    ('Sarah', 'Wilson'),
    ('Robert', 'Taylor'),
    ('Jessica', 'Brown'),
    ('William', 'Moore'),
    ('Olivia', 'Anderson');

INSERT INTO classroom (classroom_name)
VALUES
    ('Room 101'),
    ('Room 102'),
    ('Room 103'),
    ('Room 104'),
    ('Room 105'),
    ('Room 201'),
    ('Room 202'),
    ('Room 203'),
    ('Room 204'),
    ('Room 205');

INSERT INTO student (first_name, last_name, group_id)
values ('Liam', 'Jones', 2),
       ('Harper', 'Robinson', 10),
       ('Lucas', 'Thompson', 1),
       ('Carter', 'Clark', 9),
       ('Amelia', 'Martinez', 3),
       ('Isabella', 'Miller', 5),
       ('Sophia', 'Lee', 5),
       ('Mia', 'Hall', 9),
       ('Emma', 'Jones', 2),
       ('Caden', 'Smith', 5),
       ('Amelia', 'Thomas', 5),
       ('Grayson', 'Garcia', 11),
       ('Liam', 'Garcia', 2),
       ('Ava', 'Smith', 2),
       ('Abigail', 'Robinson', 5),
       ('Carter', 'Thomas', 6),
       ('Amelia', 'Rodriguez', 4),
       ('Olivia', 'Martinez', 4),
       ('Evelyn', 'Rodriguez', 2),
       ('Noah', 'Lee', 9),
       ('Olivia', 'Taylor', 3),
       ('Harper', 'Thompson', 4),
       ('Noah', 'Williams', 3),
       ('Carter', 'Lewis', 8),
       ('Caden', 'Thompson', 7),
       ('Jackson', 'Jones', 8),
       ('Sophia', 'Thomas', 6),
       ('Sophia', 'Brown', 3),
       ('Ava', 'Rodriguez', 6),
       ('Carter', 'Smith', 11),
       ('Evelyn', 'Lee', 6),
       ('Caden', 'Clark', 11),
       ('Ava', 'Hall', 5),
       ('Noah', 'Garcia', 6),
       ('Harper', 'Garcia', 6),
       ('Ava', 'Miller', 5),
       ('Harper', 'Jones', 9),
       ('Lucas', 'Taylor', 2),
       ('Sophia', 'Rodriguez', 8),
       ('Elijah', 'Williams', 4),
       ('Ava', 'Williams', 10),
       ('Emma', 'Martinez', 6),
       ('Lucas', 'Anderson', 7),
       ('Olivia', 'Davis', 10),
       ('Isabella', 'Anderson', 2),
       ('Emma', 'Taylor', 1),
       ('Lucas', 'Lee', 7),
       ('Elijah', 'Garcia', 7),
       ('Jackson', 'Robinson', 10),
       ('Olivia', 'Rodriguez', 7),
       ('Noah', 'Clark', 11),
       ('Elijah', 'Robinson', 3),
       ('Isabella', 'Thompson', 5),
       ('Olivia', 'Smith', 9),
       ('Jackson', 'Hall', 5),
       ('Amelia', 'Brown', 2),
       ('Emma', 'Brown', 10),
       ('Grayson', 'Robinson', 10),
       ('Emma', 'Clark', 6),
       ('Elijah', 'Johnson', 2),
       ('Ava', 'Thompson', 11),
       ('Caden', 'Johnson', 7),
       ('Emma', 'Smith', 8),
       ('Lucas', 'Hall', 8),
       ('Noah', 'Thompson', 9),
       ('Olivia', 'Clark', 10),
       ('Lucas', 'Smith', 1),
       ('Abigail', 'Clark', 7),
       ('Abigail', 'Garcia', 11),
       ('Amelia', 'Johnson', 8),
       ('Aiden', 'Thompson', 6),
       ('Emma', 'Robinson', 9),
       ('Elijah', 'Wilson', 8),
       ('Isabella', 'Clark', 10),
       ('Carter', 'Robinson', 10),
       ('Mia', 'Miller', 5),
       ('Elijah', 'Thomas', 3),
       ('Sophia', 'Robinson', 11),
       ('Noah', 'Taylor', 2),
       ('Elijah', 'Clark', 8),
       ('Emma', 'Thomas', 11),
       ('Oliver', 'Garcia', 10),
       ('Evelyn', 'Wilson', 3),
       ('Oliver', 'Lewis', 10),
       ('Lucas', 'Davis', 8),
       ('Oliver', 'Rodriguez', 1),
       ('Liam', 'Williams', 8),
       ('Evelyn', 'Hall', 1),
       ('Lucas', 'Jones', 9),
       ('Olivia', 'Brown', 8),
       ('Abigail', 'Wilson', 3),
       ('Emma', 'Johnson', 11),
       ('Caden', 'Robinson', 8),
       ('Mia', 'Robinson', 7),
       ('Liam', 'Brown', 3),
       ('Ava', 'Jones', 4),
       ('Liam', 'Anderson', 7),
       ('Noah', 'Miller', 10),
       ('Mia', 'Lee', 3),
       ('Evelyn', 'Johnson', 4),
       ('Harper', 'Rodriguez', 6),
       ('Abigail', 'Johnson', 8),
       ('Olivia', 'Miller', 11),
       ('Aiden', 'Jones', 9),
       ('Harper', 'Smith', 11),
       ('Caden', 'Hall', 6),
       ('Amelia', 'Thompson', 4),
       ('Sophia', 'Davis', 5),
       ('Oliver', 'Martinez', 5),
       ('Harper', 'Martinez', 1),
       ('Aiden', 'Rodriguez', 5),
       ('Lucas', 'Rodriguez', 8),
       ('Grayson', 'Anderson', 9),
       ('Caden', 'Lee', 8),
       ('Lucas', 'Martinez', 5),
       ('Jackson', 'Rodriguez', 11),
       ('Noah', 'Jones', 2),
       ('Isabella', 'Taylor', 8),
       ('Amelia', 'Jones', 2),
       ('Lucas', 'Williams', 2),
       ('Jackson', 'Anderson', 4),
       ('Carter', 'Hall', 3),
       ('Jackson', 'Brown', 5),
       ('Jackson', 'Clark', 6),
       ('Emma', 'Davis', 8),
       ('Isabella', 'Lee', 2),
       ('Carter', 'Taylor', 2),
       ('Grayson', 'Rodriguez', 6),
       ('Isabella', 'Wilson', 5),
       ('Caden', 'Davis', 10),
       ('Abigail', 'Thomas', 2),
       ('Liam', 'Johnson', 10),
       ('Carter', 'Thompson', 8),
       ('Oliver', 'Jones', 11),
       ('Oliver', 'Anderson', 5),
       ('Olivia', 'Jones', 8),
       ('Oliver', 'Miller', 8),
       ('Elijah', 'Lee', 9),
       ('Grayson', 'Jones', 6),
       ('Ava', 'Robinson', 6),
       ('Ava', 'Thomas', 1),
       ('Lucas', 'Miller', 4),
       ('Amelia', 'Anderson', 2),
       ('Abigail', 'Miller', 4),
       ('Noah', 'Davis', 10),
       ('Isabella', 'Hall', 9),
       ('Emma', 'Thompson', 1),
       ('Aiden', 'Robinson', 5),
       ('Caden', 'Rodriguez', 7),
       ('Carter', 'Miller', 11),
       ('Harper', 'Lee', 8),
       ('Ava', 'Wilson', 9),
       ('Elijah', 'Smith', 4),
       ('Amelia', 'Lewis', 2),
       ('Aiden', 'Lewis', 10),
       ('Liam', 'Thompson', 8),
       ('Aiden', 'Davis', 8),
       ('Carter', 'Jones', 2),
       ('Evelyn', 'Jones', 5),
       ('Oliver', 'Smith', 9),
       ('Elijah', 'Thompson', 8),
       ('Grayson', 'Smith', 6),
       ('Mia', 'Smith', 5),
       ('Mia', 'Lewis', 2),
       ('Elijah', 'Rodriguez', 8),
       ('Liam', 'Davis', 2),
       ('Mia', 'Rodriguez', 6),
       ('Isabella', 'Lewis', 2),
       ('Ava', 'Garcia', 9),
       ('Evelyn', 'Taylor', 1),
       ('Abigail', 'Taylor', 1),
       ('Grayson', 'Clark', 9),
       ('Aiden', 'Martinez', 2),
       ('Abigail', 'Lewis', 11),
       ('Isabella', 'Martinez', 11),
       ('Harper', 'Taylor', 9),
       ('Elijah', 'Taylor', 2),
       ('Evelyn', 'Williams', 10),
       ('Aiden', 'Smith', 3),
       ('Liam', 'Wilson', 10),
       ('Caden', 'Williams', 6),
       ('Amelia', 'Davis', 7),
       ('Carter', 'Rodriguez', 4),
       ('Lucas', 'Garcia', 8),
       ('Grayson', 'Lee', 7),
       ('Sophia', 'Johnson', 6),
       ('Abigail', 'Martinez', 8),
       ('Emma', 'Williams', 10),
       ('Jackson', 'Lee', 4),
       ('Carter', 'Garcia', 8),
       ('Carter', 'Williams', 2),
       ('Sophia', 'Taylor', 6),
       ('Emma', 'Garcia', 11),
       ('Evelyn', 'Anderson', 2),
       ('Amelia', 'Williams', 2),
       ('Caden', 'Anderson', 9),
       ('Carter', 'Davis', 10),
       ('Mia', 'Williams', 6),
       ('Caden', 'Miller', 5),
       ('Mia', 'Thomas', 8);